<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerErrCvpq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerErrCvpq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerErrCvpq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerErrCvpq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerErrCvpq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ErrCvpq',
    'container.build_id' => '7084d65e',
    'container.build_time' => 1652778331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerErrCvpq');
