<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEesYLdz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEesYLdz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEesYLdz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEesYLdz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEesYLdz\App_KernelDevDebugContainer([
    'container.build_hash' => 'EesYLdz',
    'container.build_id' => 'aacd6312',
    'container.build_time' => 1652858363,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEesYLdz');
